#!/bin/sh

export cmd='cp -p'
if [ $# -ne 0 ] ; then
  export cmd=$*
fi
echo $cmd

for ex in seaice_iceamsr2.Cd/seaice_iceamsr2 \
seaice_amsrbufr.fd/seaice_amsrbufr \
seaice_iceamsr2.Cd/amsr2_l1b_scan
do
  if [ -f $ex ] ; then
    $cmd $ex ../exec
  else
    echo could not find $ex ERROR
  fi
done
